channels:
  - conda-forge
  - defaults
dependencies:
  - configparser
  - graphviz
  - python=3.7
  - matplotlib=3.4.3
  - seaborn
  - pandas
  - geopandas
  - libpysal
  - mapclassify
  - statsmodels
  - networkx
  - spectra
  - descartes
  - scikit-learn
  - wordcloud
  - pip
  - cytoolz
  - gensim
  - pip:
    - bezier
    - scattertext
    - KDEpy
    - adjustText
    - contextily
    - matplotlib-scalebar
    - git+https://github.com/zorzalerrante/aves
    - pymunk
    - emoji
    - xlrd
